### ISSUE TITLE
Bus Error

### ISSUE THREAD

**Issue by janwirth** [hroptatyr/xls2txt#1]
Hey there.
First off: thank you.
Secondly: It does not work for me :(
```
sh-3.2$ xls2txt/xls2txt-0.15/xls2txt ES_UCui/DataRuleConfigExport_Enrichment.xls 
Bus error: 10
```
macOS Sierra 10.12.5 (16F73)
built with GNU Make 3.81

**Comment by hroptatyr** [comment]
Hey Franz,
thanks for the report.

Is there any chance you could send me the offending excel file.
Strip off confidential information.

**Comment by janwirth** [comment]
Hey Seb. I'm Jan in fact.

I'm afraid all info in this particular file is confidential.
I get the bus error on all files I tried so far.

https://www.dropbox.com/s/gcah14t3acsaljk/Workbook1.xls?dl=0

**Comment by hroptatyr** [comment]
Oh sorry Jan.  I pushed a proposed fix to master (044d81b).

The issue is unaligned access of memory but unfortunately on
the machines I usually use for that kind of thing (PowerPC, Sparc)
the issue doesn't show up.  So the proposed fix is actually just
guesswork.

**Comment by janwirth** [comment]
Alright, I will try that out and report back.

**Comment by janwirth** [comment]
```log
$ make 
cc -O2 -g -Wall -DVERSION=0.15 -c xls2txt.c -o xls2txt.o
xls2txt.c:442:1: warning: type specifier missing, defaults to 'int' [-Wimplicit-int]
print_fmt(const u8 *xfp, double v)
^
xls2txt.c:449:3: error: non-void function 'print_fmt' should return a value [-Wreturn-type]
                return;
                ^
xls2txt.c:492:2: error: non-void function 'print_fmt' should return a value [-Wreturn-type]
        return;
        ^
1 warning and 2 errors generated.
make: *** [xls2txt.o] Error 1
```

It's dead.

**Comment by hroptatyr** [comment]
Sorry, merge accident.

**Comment by janwirth** [comment]
Still get the bus error, built at 0eb28402a184bbfea77fd184fe25fa5ee6d732e1 (last commit)

**Comment by hroptatyr** [comment]
Hey Jan, finally got around to building the tool on a Mac.
e0266c0 should now work.

**Comment by janwirth** [comment]
Nope still get the bus error. :( Did you also _test_ in on mac?

Force rebuilt @ e0266c024bce9a3c30321c36576edcae81f60718

I'm sorry for bugging you abuot this :/ I don't know any C... I'm just a JS nut that's trying to provide the best workflow to his colleagues!

You supp is much appreciated.

**Comment by hroptatyr** [comment]
Yes tested on Mac.

    $ clang --version
    Apple LLVM version 7.3.0 (clang-703.0.31)
    Target: x86_64-apple-darwin15.6.0
    Thread model: posix
    InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin

https://travis-ci.org/hroptatyr/xls2txt/builds/265441648

No idea what their default Xcode version is at the moment.

**Comment by janwirth** [comment]
I have a newer clang I figured.
```
Apple LLVM version 8.1.0 (clang-802.0.42)
Target: x86_64-apple-darwin16.6.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
```

You tested it on a file, right?

**Comment by hroptatyr** [comment]
Yes, on your file.  It's now in the repo as well.  `Workbook1.xls`

The whole operating system is newer, darwin 16.6 vs darwin 15.6.
Maybe they've changed something big (the major number jumped).

Btw, travis is about to roll out a new Xcode and MacOS version soon.

**Comment by janwirth** [comment]
Can you maybe send the compiled version over so I can work with that one? :) Or will we have an architecture mismatch?

**Comment by rudimeier** [comment]
On August 17, 2017 10:45:34 AM GMT+02:00, Sebastian Freundt <notifications@github.com> wrote:
>Btw, travis is about to roll out a new Xcode and MacOS version soon.

You can force certain xcode/OSX versions on travis, using "osx_image: xcode8.3". See here https://docs.travis-ci.com/user/reference/osx/

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by hroptatyr** [comment]
The working `xls2txt` binary is on the releases page now (https://github.com/hroptatyr/xls2txt/releases).

I'm trying an Xcode8.3 build as well.

**Comment by janwirth** [comment]
The compiled version works for me. :) Thx.

**Comment by janwirth** [comment]
Side note - is it possible to output each cell on a separate line?
Or output it as XML or something like this?

**Comment by hroptatyr** [comment]
Yes, just pipe the output to `tr '\t' '\n'`, i.e.

    $ xls2txt Workbook1.xls | tr '\t' '\n'

**Comment by janwirth** [comment]
I think we can consider this fixed :) Thanks again.
